save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
client_config_file: client_secrets.json

get_refresh_token: True

oauth_scope:
  - "https://www.googleapis.com/auth/drive"